server:
  port: 8081

spring:
  application:
    name: CustomerService
  datasource:
    url: jdbc:postgresql://localhost:5432/logisticsdb
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: profile
    show-sql: true
  liquibase:
    default-schema: profile
    change-log: classpath:/db/changelog/profileChangelog.xml
