name: Maven CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Install dependencies
        run: mvn package -DskipTests
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Run Formatter
        run: mvn com.coveo:fmt-maven-plugin:format
      - name: Test
        run: mvn test